#!/bin/sh
# Buildroot + BusyBox init：由 /etc/init.d/rcS 依次执行 S??* 并传入 start
# 依赖：已安装 wifi-sta-up.sh / wifi-sta-down.sh 到 /usr/local/bin/

# 网卡名与 systemd 版一致，改成 wlan1 等时只改这里即可
export WLAN_IF=wlan0

case "$1" in
start)
	if [ ! -f /etc/wpa_supplicant.conf ]; then
		exit 0
	fi
	/usr/local/bin/wifi-sta-up.sh || true
	;;
stop)
	/usr/local/bin/wifi-sta-down.sh || true
	;;
restart)
	"$0" stop
	"$0" start
	;;
*)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1
	;;
esac
exit 0
